### ISSUE TITLE
Is it possible to map a slot with a lookup of different values

### ISSUE THREAD

**Issue by rahul-idexcel** [monologg/JointBERT#10]
I am facing a issue as my slot has large number of values. I am looking for a way to map my slot to a lookup so that we need not put all the categories in the slot while training.

If there is a way please let me know . Thanks in advance.

**Comment by monologg** [comment]
You mean that the **number of classes for slot** is too big and it makes an memory overflow? I'm sorry that I have no idea how to care this issue while training:(

**Comment by rahul-idexcel** [comment]
No its not about memory flow or something...its just that a slot can have too many categories ex:-take location slot ..it can have hundreds of values as location 
So, we cannot go and mention each value in the seq.in and seq.out as its mapping ...is there a way that we can assign a slot that it has x,y,z etc. values which ever come against that slot gets picked up automatically.

Example:- 
If a slot Location has values:-
[CA,NY,MD,GA,AZ,IL,NC..etc]
and we have not mentioned all values in training against location slot ...is there a way to map a slot to dynamically pick any values which come from this list in a user query.

 Can a particular slot lookup into a list while predicting the the user query if the particular value has not been trained in the training data.

**Comment by monologg** [comment]
I think the example will be impossible within this repo because this code is based on `supervised learning` and I have no idea how to map a slot dynamically which come from user query.

I recommend you to categorize all of them to `LOC` tags, and if the label is `LOC` tag, then you should send the word to `another kind of classifier` to classify Canada, Newyork etc. (it shouldn't have to be deep learning classifier). I think this will be the way to cover this issue in the boundary of supervised learning.

**Comment by monologg** [comment]
I'll close this issue. Feel free to reopen if I haven't fully answered your questions.
